import os
import streamlit as st
import logging

# Ensure dotenv is loaded
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

import main

# ============================================================
# SYSTEM PROMPTS FOR DEPLOYMENT BRIEFINGS
# ============================================================

WEATHER_AGENT_SYSTEM_PROMPT = """ROLE: 
You are the Meteorological Analyst Specialist for an Airline-Grade Multi-Agent Flight Operations Copilot. Your job is to analyze raw aviation weather reports (METAR/TAF) and generate a safety-critical pilot briefing.

OPERATIONAL INSTRUCTIONS & CONSTRAINTS:
1. TIMELINE DECOUPLING: When evaluating TAF forecast periods (indicated by FM, TEMPO, or PROB30), treat each time block as its own independent weather environment. Do not apply the temperature of the initial daytime observation to a freezing forecast block hours later. Never write that the airport is "currently experiencing" a hazard if that hazard is only predicted in a future forecast block.
2. GEOGRAPHIC ISOLATION: Stick strictly to the environment of the requested airport ICAO code. Never pull, mention, or cross-contaminate runway data, layouts, or headings belonging to other global airports (e.g., if analyzing EHAM, do not reference runways or rules for KJFK or KORD).
3. AVIATION ABBREVIATION DICTIONARY: Standard aviation decoding vocabulary must be strictly enforced. Correctly decode 'BR' as Mist (not Brilliant Reflectivity), 'HZ' as Haze, and '-SN'/'SN' as Light Snow/Snow.
4. ICING HAZARDS: If you detect active freezing or frozen moisture codes (such as FZFG, FZRA, SN, -SN, or BLSN) alongside temperatures at or below 0°C, you must explicitly flag a high-priority "Severe Ground Icing Alert" and recommend mandatory Type I/IV fluid de-icing procedures.
5. WIND LIMITATIONS: Actively parse the wind speeds and gust thresholds (indicated by 'G'). If gusts exceed 20 knots, explicitly note the threat of severe wind gusts and advise cross-checking aircraft-specific crosswind limits.

OUTPUT FORMAT REQUIREMENTS:
- Use clear markdown headers (### Safety Considerations, ### Operational Recommendations, ### Limitations).
- Keep your sentences highly concise, professional, and tailored for flight crews under high-pressure scenarios."""

PERFORMANCE_AGENT_SYSTEM_PROMPT = """ROLE:
You are the Aircraft Performance and Weight & Balance Engineer Specialist for the Multi-Agent Flight Copilot pipeline. Your job is to calculate structural weights, environmental degradation factors, and legal runway stopping requirements.

CRITICAL PERFORMANCE & WEIGHT CONSTRAINTS:
1. TAXI VS. TAKEOFF WEIGHT LOGIC: Taxi-out fuel burn is a small, realistic margin (typically 200 kg to 500 kg for commercial narrow-body aircraft like the Boeing 737-800). Never assume or calculate that an aircraft burns large percentages or halves of its fuel tank during the taxi-out or takeoff phases.
2. TOW VS. MTOW GO/NO-GO GATE: If the calculated Takeoff Weight (TOW) exceeds the Maximum Structural Takeoff Weight (MTOW), you MUST issue a prominent, high-priority bold warning: "**CRITICAL WEIGHT VIOLATION - AIRCRAFT OVERWEIGHT FOR TAKEOFF**". Never minimize or justify a takeoff weight violation by pointing to a compliant landing weight or fuel burn. If TOW > MTOW, the flight is legally grounded.
3. EMPIRICAL FORMULA UNIT DISCIPLINE: When solving empirical performance formulas (such as runway landing distance equations), treat the variables (Weight, Wind, Temp) as pure, unitless scalars during the math execution steps. Do not append strings like "kg" or "KT" inside the middle of math steps, which leads to nonsense algebraic errors (e.g., adding kg to knots). The final computed value must strictly resolve to the single target measurement unit (e.g., Feet or Meters).
4. PERFORMANCE RETRIEVAL BOUNDS: Do not perform manual wind geometry or relative crosswind angle math here; rely entirely on the outputs generated by the crosswind mathematical helper modules or explicitly state the missing variables.

OUTPUT FORMAT REQUIREMENTS:
- Present all structural weight breakdowns (ZFW, Fuel, Payload, TOW, MTOW) in a clean, scannable Markdown Table for rapid verification."""

VALIDATOR_AGENT_SYSTEM_PROMPT = """ROLE:
You are the Automated Safety Inspector and Quality Control Guardrail Agent. You intercept the combined output draft generated by the specialized agents and audit it against raw telemetry data.

MANDATORY ANTI-CONFLATION & SAFETY RULES:
1. RUNWAY VISUAL RANGE (RVR) COGNIZANCE: RVR (e.g., R18R/0800FT) dictates horizontal visibility parameters down the runway centerline for instrument approach categories. It has ZERO correlation with tire hydroplaning, braking action coefficients, or water/slush depth. If you find any instance where the draft associates low RVR values with braking degradation or braking performance risks, you must strip or correct that text immediately.
2. ACCURATE CALCULATED CROSSWINDS: Cross-reference any crosswind assertions with deterministic geometry: Crosswind = Gust Speed * sin(Relative Angle). If a draft claims a wind closely aligned with a runway heading (e.g., 10-degree offset) will "exceed crosswind limitations," intercept and inject a metric correction stating the crosswind is mathematically negligible and acts as a safe headwind.
3. TAILWIND EVALUATION: If the relative wind angle to the target runway is greater than 90°, evaluate the tailwind component: Tailwind = Wind Speed * cos(Relative Angle). If the tailwind component exceeds 10–15 knots, inject an explicit **CRITICAL TAILWIND LIMIT EXCEEDED** warning, as this violates standard narrow-body aircraft structural limits."""


# Title and Layout
st.set_page_config(
    page_title="Flight Operations CoPilot",
    page_icon="✈️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Glassmorphic CSS Styling
st.markdown("""
<style>
    /* Styling settings for dark mode glassmorphism look */
    .stApp {
        background: radial-gradient(circle at 50% 50%, #1a1c29 0%, #0d0e15 100%);
        color: #e2e8f0;
    }
    .main-title {
        font-family: 'Outfit', 'Inter', sans-serif;
        background: linear-gradient(135deg, #00f2fe 0%, #4facfe 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 2.8rem;
        font-weight: 800;
        text-align: center;
        margin-bottom: 2rem;
    }
    .glass-card {
        background: rgba(255, 255, 255, 0.03);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 16px;
        padding: 1.5rem;
        backdrop-filter: blur(10px);
        margin-bottom: 1.5rem;
    }
    .agent-header {
        font-weight: 700;
        font-size: 1.2rem;
        margin-bottom: 10px;
    }
</style>
""", unsafe_allow_html=True)

# Page header
st.markdown("<div class='main-title'>✈️ AI Flight Operations CoPilot</div>", unsafe_allow_html=True)

# Initialize Session State Agent
@st.cache_resource
def get_ops_agent():
    return main.OpsCopilotAgent()

with st.spinner("Initializing Flight Operations System... (Index Verification in progress)"):
    agent = get_ops_agent()

# Sidebar config
with st.sidebar:
    st.markdown("### ⚙️ System Configuration")
    
    # Show active LLM client type
    has_groq = bool(os.environ.get("GROQ_API_KEY"))
    if has_groq:
        st.success("🟢 LLM Client: Groq Cloud API")
        st.caption(f"Model: {os.environ.get('GROQ_MODEL', 'llama-3.1-8b-instant')}")
    else:
        st.warning("🔵 LLM Client: Local Ollama")
        st.caption("Model: qwen3:8b")
        
    st.markdown("---")
    st.markdown("### 💡 Try these Queries:")
    st.code("KJFK 142351Z 34018G30KT 1/2SM R04R/2000FT -SN BLSN FZFG OVC008 M08/M09 A2982")
    st.code("What are the active runway headings for airport VOMM?")
    st.code("Calculate landing distance for a B738 on dry runway at sea level, 65,000 kg.")

# User Input
st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
query = st.text_input("Enter your flight operations query or METAR code:", placeholder="e.g. KDEN 142253Z 02022G35KT 3/4SM -SN BLSN FZFG")
submit = st.button("Analyze & Dispatch", type="primary")
st.markdown("</div>", unsafe_allow_html=True)

if submit and query:
    with st.spinner("Processing Agent Routing..."):
        try:
            # Classify Intent
            intent = agent.classify_intent(query)
            
            # Map Agent Name
            agent_map = {
                "WEATHER": "WeatherAgent (Meteorological Analyst)",
                "RAG": "RAGAgent (Operations Manual Retriever)",
                "CALCULATOR": "PerformanceAgent (Flight Calculator)",
                "DECISION": "DecisionAgent (Command Orchestrator)"
            }
            routed_agent = agent_map.get(intent, "DecisionAgent (Command Orchestrator)")
            
            # Columns for Routing Metadata
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Routed Specialist", routed_agent)
            with col2:
                st.metric("Classified Intent", intent)
                
            # Execute Agent Pipeline
            response = agent.run(query)
            
            # Output Display Card
            st.markdown("### 📋 Copilot Resolution Output")
            st.markdown(f"<div class='glass-card'>{response}</div>", unsafe_allow_html=True)
            
        except Exception as e:
            st.error(f"Execution Error: {e}")
